### ISSUE TITLE
crash at exit with LDC

### ISSUE THREAD

**Issue by rtbo** [atilaneves/unit-threaded#238]
When the main function mixed-in by `runTestsMain` exits, it crashes due to a `pthread` related problem.
It occurs with LDC, but not with DMD.

Platform: Linux x86_64.
Compiler: LDC-1.24.0

Steps to reproduce:
```sh
git clone https://github.com/rtbo/unitthreaded_crash
cd unitthreaded_crash
dub test --compiler=ldc
```
output:
```
Running custom 'unittest' configuration.
......
Running ./libtest 
lib.times_three.unittest_L9:
lib.times_two.unittest_L9:

Time taken: 265 μs and 2 hnsecs
2 test(s) run, 0 failed.

OK!

Aborting from core/sync/mutex.d(149) Error: pthread_mutex_destroy failed.Program exited with code -6
```
GDB backtrace:
```
(gdb) bt
#0  0x00007ffff76f3615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff76dc862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7abba20 in core.internal.abort.abort(scope immutable(char)[], scope immutable(char)[], ulong) ()
   from /usr/lib/libdruntime-ldc-shared.so.94
#3  0x00007ffff7ac8ac3 in core.sync.mutex.Mutex.~this() () from /usr/lib/libdruntime-ldc-shared.so.94
#4  0x00007ffff7aed157 in rt_finalize2 () from /usr/lib/libdruntime-ldc-shared.so.94
#5  0x00007ffff7ad527d in gc.impl.conservative.gc.SmallObjectPool.runFinalizers(scope const(void[])) () from /usr/lib/libdruntime-ldc-shared.so.94
#6  0x00007ffff7ad35eb in gc.impl.conservative.gc.Gcx.runFinalizers(scope const(void[])) () from /usr/lib/libdruntime-ldc-shared.so.94
#7  0x00007ffff7ad36b1 in gc.impl.conservative.gc.ConservativeGC.runLocked!(gc.impl.conservative.gc.ConservativeGC.runFinalizers(scope const(void[])).go(gc.impl.conservative.gc.Gcx*, scope const(void[])), gc.impl.conservative.gc.otherTime, gc.impl.conservative.gc.numOthers, gc.impl.conservative.gc.Gcx*, const(void[])).runLocked(ref gc.impl.conservative.gc.Gcx*, ref const(void[])) () from /usr/lib/libdruntime-ldc-shared.so.94
#8  0x00007ffff7ad48e3 in _DThn16_2gc4impl12conservativeQw14ConservativeGC13runFinalizersMFNbMxAvZv () from /usr/lib/libdruntime-ldc-shared.so.94
#9  0x00007ffff7af494c in _d_dso_registry () from /usr/lib/libdruntime-ldc-shared.so.94
#10 0x00007ffff7aa920b in ldc.register_dso () from /usr/lib/libdruntime-ldc-shared.so.94
#11 0x00007ffff7fe168b in _dl_fini () from /lib64/ld-linux-x86-64.so.2
#12 0x00007ffff76f5db7 in __run_exit_handlers () from /usr/lib/libc.so.6
#13 0x00007ffff76f5f5e in exit () from /usr/lib/libc.so.6
#14 0x00005555555820d3 in D main (args=...)
    at /home/remi/dev/test/unitthreaded_crash/../../../.dub/packages/unit-threaded-1.0.11/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d:43
```

**Comment by atilaneves** [comment]
Closed by #236
